version: '3.8'

services:
  app1:
    build: .
    ports:
      - "7001:7000"
    environment:
      - APP_NAME=app_1

  app2:
    build: .
    ports:
      - "7002:7000"
    environment:
      - APP_NAME=app_2

  app3:
    build: .
    ports:
      - "7003:7000"
    environment:
      - APP_NAME=app_3